{{- if and .Values.config.db.host .Values.config.db.user .Values.config.db.password .Values.config.db.name .Values.config.db.port }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gobio.dbSecretName" . }}
type: Opaque
data:
  host: {{ .Values.config.db.host | b64enc }}
  user: {{ .Values.config.db.user | b64enc }}
  password: {{ .Values.config.db.password | b64enc }}
  name: {{ .Values.config.db.name | b64enc }}
  port: {{ .Values.config.db.port | b64enc }}

---
{{- end }}
{{- if .Values.config.jwt.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gobio.jwtSecretName" . }}
type: Opaque
data:
  secretKey: {{ .Values.config.jwt.secretKey | b64enc }}

---
{{- end }}
