name: Run tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ["1.18", "1.17"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: ${{ matrix.go_version }}
      - name: Download dependencies
        run: go mod download
      - name: Verify dependencies
        run: go mod verify
      - name: Run tests
        run: go test -v -race ./...
      - name: Build
        run: go build -v ./...
